version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"  
      - "9000:9000"  
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"  
      - "7077:7077"  
    environment:
      - SPARK_MODE=master
      - HOME=/tmp
      - USER_HOME=/tmp
    volumes:
      - .:/app
      - ./libs/clickhouse-jdbc-0.3.2-shaded.jar:/opt/bitnami/spark/jars/clickhouse-jdbc.jar
    depends_on:
      - clickhouse

  spark-worker:
    image: bitnami/spark:latest
    depends_on:
      - spark-master
    volumes:
      - ./libs/clickhouse-jdbc-0.3.2-shaded.jar:/opt/bitnami/spark/jars/clickhouse-jdbc.jar
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  analytics_etl:
    build: .
    depends_on:
      - spark-master
      - clickhouse
    volumes:
      - .:/app
    environment:
      - CLICKHOUSE_HOST=clickhouse
    command: ["python", "/app/spark_job.py"]

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase.db
    volumes:
      - metabase_data:/metabase.db
    depends_on:
      - clickhouse

volumes:
  clickhouse_data:
  metabase_data: